const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  // //admin
  // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
  // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_GENDER_REQUEST: "FETCH_GENDER_REQUEST",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILURE: "FETCH_GENDER_FAILURE",

  FETCH_ROLE_REQUEST: "FETCH_ROLE_REQUEST",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILURE: "FETCH_ROLE_FAILURE",

  FETCH_POSITION_REQUEST: "FETCH_POSITION_REQUEST",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILURE: "FETCH_POSITION_FAILURE",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILURE: "FETCH_ALL_USER_FAILURE",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILURE: "EDIT_USER_FAILURE",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILURE: "FETCH_TOP_DOCTOR_FAILURE",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILURE: "FETCH_ALL_DOCTOR_FAILURE",

  SAVE_INFO_DOCTOR_SUCCESS: "SAVE_INFO_DOCTOR_SUCCESS",
  SAVE_INFO_DOCTOR_FAILURE: "SAVE_INFO_DOCTOR_FAILURE",

  FEATCH_ALLCODE_SCHEDULE_TIME_SUCCESS: "FEATCH_ALLCODE_SCHEDULE_TIME_SUCCESS",
  FEATCH_ALLCODE_SCHEDULE_TIME_FAILURE: "FEATCH_ALLCODE_SCHEDULE_TIME_FAILURE",

  FETCH_REQUIRED_SUCCESS: "FETCH_REQUIRED_SUCCESS",
  FETCH_REQUIRED_FAILURE: "FETCH_REQUIRED_FAILURE",
});

export default actionTypes;
